begin;

insert into public.system_process_registry (
  process_key,
  process_family,
  title,
  status,
  source_path,
  authority_state,
  metadata,
  process_title,
  process_scope,
  process_status,
  authority_level,
  source_reference_set,
  required_oar_type,
  requires_operator_confirm,
  requires_preflight,
  requires_oar1_closeout
) values (
  'new_moon_to_lions_gate_2026',
  'c3_field_priority_initiative',
  'New Moon to Lion''s Gate Inanna SEAT Initiative',
  'active',
  'docs/oar/c3_field/oar2_register_new_moon_to_lions_gate_inanna_seat_initiative_v1.meta.md',
  'execution_authority_registered',
  '{
    "initiative_alias": "register.SEAT Inannitiative",
    "window_open": "2026-07-14",
    "window_close": "2026-08-08",
    "priority": "primary",
    "active_branch": "measures_of_inanna",
    "successor_branch": "priceless_gallery",
    "cutover_authority": "operator_gated",
    "lions_gate_release": "separate_operator_gated_process",
    "legacy_runtime": "remains_active_until_verified_free_cutover",
    "dashboard_standing": "read_only",
    "process_execution_standing": "operator_gated",
    "free_cutover_authorized": false,
    "public_release_authorized": false,
    "legacy_runtime_retirement_authorized": false,
    "priceless_gallery_launch_authorized": false,
    "milestones": [
      {"window": "2026-07-14/2026-07-18", "standing": "initiative_registration_executor_advisement_current_state_inventory"},
      {"window": "2026-07-19/2026-07-25", "standing": "registry_reconciliation_artwork_phase_calendar_process_dashboard_foundation"},
      {"window": "2026-07-26/2026-08-01", "standing": "free_profiles_parallel_rendering_resolver_phase_map_dashboard_readiness"},
      {"window": "2026-08-02/2026-08-06", "standing": "qa_deployment_rollback_lions_gate_packet"},
      {"window": "2026-08-07", "standing": "operator_cutover_decision_gate"},
      {"window": "2026-08-08", "standing": "separate_lions_gate_release_and_successor_confirmation"}
    ],
    "operator_decision_gates": ["august_7_cutover_decision", "august_8_lions_gate_release_separate_authority", "rollback_decision_operator_only"]
  }'::jsonb,
  'New Moon to Lion''s Gate Inanna SEAT Initiative',
  'c3_field_priority_initiative_registration',
  'active',
  'execution_authority',
  '[
    {"surface": "source_oar2", "path": "docs/oar/c3_field/oar2_register_new_moon_to_lions_gate_inanna_seat_initiative_v1.meta.md"},
    {"surface": "active_branch", "key": "measures_of_inanna"},
    {"surface": "successor_branch", "key": "priceless_gallery"},
    {"surface": "role_contracts", "keys": ["chazz_systems_advisement_new_moon_to_lions_gate_2026", "claude_codex_database_advisement_new_moon_to_lions_gate_2026", "cody_source_free_advisement_new_moon_to_lions_gate_2026"]},
    {"surface": "evidence_contracts", "keys": ["chazz_systems_evidence_new_moon_to_lions_gate_2026", "claude_codex_database_evidence_new_moon_to_lions_gate_2026", "cody_source_free_evidence_new_moon_to_lions_gate_2026"]},
    {"surface": "baseline", "path": "docs/oar/c3_field/baseline_new_moon_to_lions_gate_inanna_seat_initiative_v1.meta.md"},
    {"surface": "oar1", "path": "docs/oar/c3_field/oar1_register_new_moon_to_lions_gate_inanna_seat_initiative_v1.meta.md"}
  ]'::jsonb,
  'both',
  true,
  true,
  true
) on conflict (process_key) do update set
  process_family = excluded.process_family,
  title = excluded.title,
  status = excluded.status,
  source_path = excluded.source_path,
  authority_state = excluded.authority_state,
  metadata = excluded.metadata,
  process_title = excluded.process_title,
  process_scope = excluded.process_scope,
  process_status = excluded.process_status,
  authority_level = excluded.authority_level,
  source_reference_set = excluded.source_reference_set,
  required_oar_type = excluded.required_oar_type,
  requires_operator_confirm = excluded.requires_operator_confirm,
  requires_preflight = excluded.requires_preflight,
  requires_oar1_closeout = excluded.requires_oar1_closeout;

insert into public.c3_role_contract (
  role_key,
  system_key,
  role_scope,
  role_name,
  role_state,
  runtime_authority_allowed,
  mutation_authority_allowed,
  review_authority_allowed,
  operator_confirmation_required,
  source_oar2_path,
  source_oar1_path,
  metadata,
  is_active
) values
(
  'chazz_systems_advisement_new_moon_to_lions_gate_2026',
  'c3_field',
  'system',
  'Chazz Systems Advisement - New Moon to Lion''s Gate 2026',
  'active',
  false,
  false,
  true,
  true,
  'docs/oar/c3_field/oar2_register_new_moon_to_lions_gate_inanna_seat_initiative_v1.meta.md',
  'docs/oar/c3_field/oar1_register_new_moon_to_lions_gate_inanna_seat_initiative_v1.meta.md',
  '{"initiative_key":"new_moon_to_lions_gate_2026","execution_surface":"systems_validation_and_advisement","not_native_nine_role":true,"does_not_replace_codex_or_operator_authority":true,"limitations":["no_independent_scope_expansion","no_release_authority","no_operator_override"]}'::jsonb,
  true
),
(
  'claude_codex_database_advisement_new_moon_to_lions_gate_2026',
  'c3_field',
  'system',
  'Claude Codex Database Advisement - New Moon to Lion''s Gate 2026',
  'active',
  false,
  false,
  true,
  true,
  'docs/oar/c3_field/oar2_register_new_moon_to_lions_gate_inanna_seat_initiative_v1.meta.md',
  'docs/oar/c3_field/oar1_register_new_moon_to_lions_gate_inanna_seat_initiative_v1.meta.md',
  '{"initiative_key":"new_moon_to_lions_gate_2026","execution_surface":"codex_database_advisement","not_native_nine_role":true,"bounded_execution_only_from_approved_oar2":true,"mutation_authority_independent":false,"limitations":["advises_before_execution","no_release_authority","no_scope_expansion"]}'::jsonb,
  true
),
(
  'cody_source_free_advisement_new_moon_to_lions_gate_2026',
  'c3_field',
  'system',
  'Cody Source and FREE Advisement - New Moon to Lion''s Gate 2026',
  'active',
  false,
  false,
  true,
  true,
  'docs/oar/c3_field/oar2_register_new_moon_to_lions_gate_inanna_seat_initiative_v1.meta.md',
  'docs/oar/c3_field/oar1_register_new_moon_to_lions_gate_inanna_seat_initiative_v1.meta.md',
  '{"initiative_key":"new_moon_to_lions_gate_2026","execution_surface":"source_free_advisement","not_native_nine_role":true,"bounded_execution_only_from_approved_oar2":true,"mutation_authority_independent":false,"limitations":["advises_before_runtime_mutation","no_release_authority","no_scope_expansion"]}'::jsonb,
  true
)
on conflict (role_key) do update set
  system_key = excluded.system_key,
  role_scope = excluded.role_scope,
  role_name = excluded.role_name,
  role_state = excluded.role_state,
  runtime_authority_allowed = excluded.runtime_authority_allowed,
  mutation_authority_allowed = excluded.mutation_authority_allowed,
  review_authority_allowed = excluded.review_authority_allowed,
  operator_confirmation_required = excluded.operator_confirmation_required,
  source_oar2_path = excluded.source_oar2_path,
  source_oar1_path = excluded.source_oar1_path,
  metadata = excluded.metadata,
  is_active = excluded.is_active;

insert into public.c3_evidence_contract (
  evidence_key,
  system_key,
  evidence_scope,
  evidence_state,
  evidence_required,
  source_required,
  operator_attestation_required,
  execution_artifact_required,
  public_claim_allowed,
  source_oar2_path,
  source_oar1_path,
  metadata,
  is_active
) values
(
  'chazz_systems_evidence_new_moon_to_lions_gate_2026',
  'c3_field',
  'system',
  'ready',
  true,
  true,
  true,
  true,
  false,
  'docs/oar/c3_field/oar2_register_new_moon_to_lions_gate_inanna_seat_initiative_v1.meta.md',
  'docs/oar/c3_field/oar1_register_new_moon_to_lions_gate_inanna_seat_initiative_v1.meta.md',
  '{"initiative_key":"new_moon_to_lions_gate_2026","executor_role_key":"chazz_systems_advisement_new_moon_to_lions_gate_2026","required_fields":["executor_role_key","execution_surface","observation_or_execution_time","target_environment","evidence_type","artifact_location","oar_association","verification_standing","limitations","operator_acceptance"],"cross_role_evidence_rule":"accepted_only_when_attribution_remains_exact"}'::jsonb,
  true
),
(
  'claude_codex_database_evidence_new_moon_to_lions_gate_2026',
  'c3_field',
  'system',
  'ready',
  true,
  true,
  true,
  true,
  false,
  'docs/oar/c3_field/oar2_register_new_moon_to_lions_gate_inanna_seat_initiative_v1.meta.md',
  'docs/oar/c3_field/oar1_register_new_moon_to_lions_gate_inanna_seat_initiative_v1.meta.md',
  '{"initiative_key":"new_moon_to_lions_gate_2026","executor_role_key":"claude_codex_database_advisement_new_moon_to_lions_gate_2026","required_fields":["executor_role_key","execution_surface","observation_or_execution_time","target_environment","evidence_type","artifact_location","oar_association","verification_standing","limitations","operator_acceptance"],"cross_role_evidence_rule":"accepted_only_when_attribution_remains_exact"}'::jsonb,
  true
),
(
  'cody_source_free_evidence_new_moon_to_lions_gate_2026',
  'c3_field',
  'system',
  'ready',
  true,
  true,
  true,
  true,
  false,
  'docs/oar/c3_field/oar2_register_new_moon_to_lions_gate_inanna_seat_initiative_v1.meta.md',
  'docs/oar/c3_field/oar1_register_new_moon_to_lions_gate_inanna_seat_initiative_v1.meta.md',
  '{"initiative_key":"new_moon_to_lions_gate_2026","executor_role_key":"cody_source_free_advisement_new_moon_to_lions_gate_2026","required_fields":["executor_role_key","execution_surface","observation_or_execution_time","target_environment","evidence_type","artifact_location","oar_association","verification_standing","limitations","operator_acceptance"],"cross_role_evidence_rule":"accepted_only_when_attribution_remains_exact"}'::jsonb,
  true
)
on conflict (evidence_key) do update set
  system_key = excluded.system_key,
  evidence_scope = excluded.evidence_scope,
  evidence_state = excluded.evidence_state,
  evidence_required = excluded.evidence_required,
  source_required = excluded.source_required,
  operator_attestation_required = excluded.operator_attestation_required,
  execution_artifact_required = excluded.execution_artifact_required,
  public_claim_allowed = excluded.public_claim_allowed,
  source_oar2_path = excluded.source_oar2_path,
  source_oar1_path = excluded.source_oar1_path,
  metadata = excluded.metadata,
  is_active = excluded.is_active;

insert into public.c3_oar_process_instance (
  process_instance_key,
  source_oar2_path,
  source_oar2_standing,
  expected_oar1_path,
  actual_oar1_path,
  evidence_path,
  lifecycle_type,
  execution_standing,
  validation_standing,
  deploy_standing,
  held_standing,
  seeded_reference_standing,
  validation_finding,
  correction_scope,
  execution_result
) values (
  'new_moon_to_lions_gate_2026_initiative_registration',
  'docs/oar/c3_field/oar2_register_new_moon_to_lions_gate_inanna_seat_initiative_v1.meta.md',
  'confirmed',
  'docs/oar/c3_field/oar1_register_new_moon_to_lions_gate_inanna_seat_initiative_v1.meta.md',
  'docs/oar/c3_field/oar1_register_new_moon_to_lions_gate_inanna_seat_initiative_v1.meta.md',
  'docs/oar/c3_field/baseline_new_moon_to_lions_gate_inanna_seat_initiative_v1.meta.md',
  'valid',
  'completed',
  'pending_validation',
  'not_authorized',
  null,
  'seeded',
  'Initiative registration completed with implementation scope held for follow-on OAR2.',
  'Next OAR2 required before register_SEAT inventory, branch reconciliation, artwork intake, process vocabulary, dashboard read model, or FREE admission discovery mutations.',
  'Initiative, executor role standing, evidence contract standing, and baseline route registered. No FREE cutover, release, Phase Calendar mutation, held encounter activation, legacy retirement, or Priceless Gallery launch performed.'
) on conflict (process_instance_key) do update set
  source_oar2_path = excluded.source_oar2_path,
  source_oar2_standing = excluded.source_oar2_standing,
  expected_oar1_path = excluded.expected_oar1_path,
  actual_oar1_path = excluded.actual_oar1_path,
  evidence_path = excluded.evidence_path,
  lifecycle_type = excluded.lifecycle_type,
  execution_standing = excluded.execution_standing,
  validation_standing = excluded.validation_standing,
  deploy_standing = excluded.deploy_standing,
  held_standing = excluded.held_standing,
  seeded_reference_standing = excluded.seeded_reference_standing,
  validation_finding = excluded.validation_finding,
  correction_scope = excluded.correction_scope,
  execution_result = excluded.execution_result;

insert into public.c3_oar_transition_event (
  transition_event_key,
  process_instance_key,
  actor,
  from_status,
  to_status,
  transition_type,
  "timestamp",
  evidence_reference,
  notes
) values
(
  'new_moon_to_lions_gate_2026_operator_approved',
  'new_moon_to_lions_gate_2026_initiative_registration',
  'operator',
  'not_queued',
  'confirmed',
  'queue',
  '2026-07-14T00:00:00-05:00',
  'docs/oar/c3_field/oar2_register_new_moon_to_lions_gate_inanna_seat_initiative_v1.meta.md',
  'OAR2 approved initiative registration, discovery, role/evidence standing, baseline capture, and next route formation.'
),
(
  'new_moon_to_lions_gate_2026_cody_registration_completed',
  'new_moon_to_lions_gate_2026_initiative_registration',
  'cody',
  'confirmed',
  'completed',
  'execution',
  now(),
  'docs/oar/c3_field/oar1_register_new_moon_to_lions_gate_inanna_seat_initiative_v1.meta.md',
  'Registration route completed with follow-on implementation mutations held.'
)
on conflict (transition_event_key) do nothing;

insert into public.system_oar_queue (
  queue_key,
  process_key,
  oar_key,
  oar_type,
  queue_status,
  operator_key,
  system_key,
  scope_key,
  requested_action,
  execution_boundary,
  preflight_status,
  operator_confirmed_at,
  execution_started_at,
  execution_completed_at,
  blocked_reason,
  refusal_reason,
  oar1_path,
  source_oar2_path,
  expected_oar1_path,
  automation_permissions,
  cody_handoff_prompt,
  chazz_review_prompt,
  chazz_review_prompt_generated_at,
  chazz_review_prompt_authority,
  execution_summary,
  db_mutation_standing,
  src_mutation_standing,
  deploy_standing
) values (
  'new_moon_to_lions_gate_2026_registration_queue',
  'new_moon_to_lions_gate_2026',
  'oar2_register_new_moon_to_lions_gate_inanna_seat_initiative_v1',
  'oar2',
  'completed',
  'op044',
  'c3_field',
  'c3_field_priority_initiative_registration',
  'Register initiative, executor standing, evidence contracts, and baseline only.',
  'No FREE cutover, no public release, no legacy retirement, no Phase Calendar mutation, no held encounter activation, no Priceless Gallery launch.',
  'passed',
  '2026-07-14T00:00:00-05:00',
  now(),
  now(),
  null,
  null,
  'docs/oar/c3_field/oar1_register_new_moon_to_lions_gate_inanna_seat_initiative_v1.meta.md',
  'docs/oar/c3_field/oar2_register_new_moon_to_lions_gate_inanna_seat_initiative_v1.meta.md',
  'docs/oar/c3_field/oar1_register_new_moon_to_lions_gate_inanna_seat_initiative_v1.meta.md',
  '{"db_registration":true,"src_mutation":false,"deploy":false,"public_cutover":false,"release":false}'::jsonb,
  'Proceed only from OAR2 authority. Preserve legacy runtime and held release states. Return OAR1 evidence.',
  'Review initiative registration and held implementation boundary before next OAR2.',
  now(),
  'thread_prompt_only',
  'Initiative registration completed; implementation mutations remain held for follow-on OAR2.',
  'mutated',
  'not_applicable',
  'not_authorized'
) on conflict (queue_key) do update set
  process_key = excluded.process_key,
  oar_key = excluded.oar_key,
  oar_type = excluded.oar_type,
  queue_status = excluded.queue_status,
  operator_key = excluded.operator_key,
  system_key = excluded.system_key,
  scope_key = excluded.scope_key,
  requested_action = excluded.requested_action,
  execution_boundary = excluded.execution_boundary,
  preflight_status = excluded.preflight_status,
  operator_confirmed_at = excluded.operator_confirmed_at,
  execution_started_at = excluded.execution_started_at,
  execution_completed_at = excluded.execution_completed_at,
  blocked_reason = excluded.blocked_reason,
  refusal_reason = excluded.refusal_reason,
  oar1_path = excluded.oar1_path,
  source_oar2_path = excluded.source_oar2_path,
  expected_oar1_path = excluded.expected_oar1_path,
  automation_permissions = excluded.automation_permissions,
  cody_handoff_prompt = excluded.cody_handoff_prompt,
  chazz_review_prompt = excluded.chazz_review_prompt,
  chazz_review_prompt_generated_at = excluded.chazz_review_prompt_generated_at,
  chazz_review_prompt_authority = excluded.chazz_review_prompt_authority,
  execution_summary = excluded.execution_summary,
  db_mutation_standing = excluded.db_mutation_standing,
  src_mutation_standing = excluded.src_mutation_standing,
  deploy_standing = excluded.deploy_standing;

insert into public.system_oar_execution_evidence (
  evidence_key,
  queue_key,
  evidence_type,
  evidence_summary,
  validation_query,
  validation_result,
  artifact_path,
  commit_hash
) values
(
  'new_moon_to_lions_gate_2026_registration_process_readback',
  'new_moon_to_lions_gate_2026_registration_queue',
  'db_query',
  'Initiative process row registered with active branch, successor branch, critical path, decision gates, and held cutover/release standing.',
  'select process_key, process_family, process_status, authority_level, metadata from public.system_process_registry where process_key = ''new_moon_to_lions_gate_2026''',
  '{"expected_process_key":"new_moon_to_lions_gate_2026","expected_process_status":"active","expected_authority_level":"execution_authority"}'::jsonb,
  'docs/oar/c3_field/register_new_moon_to_lions_gate_inanna_seat_initiative_v1.sql',
  null
),
(
  'new_moon_to_lions_gate_2026_role_contract_readback',
  'new_moon_to_lions_gate_2026_registration_queue',
  'db_query',
  'Three system execution/advisement identities registered in c3_role_contract outside the native nine-role registry.',
  'select role_key, role_state, review_authority_allowed, operator_confirmation_required from public.c3_role_contract where role_key like ''%new_moon_to_lions_gate_2026''',
  '{"expected_role_count":3,"native_nine_role_registry_altered":false}'::jsonb,
  'docs/oar/c3_field/register_new_moon_to_lions_gate_inanna_seat_initiative_v1.sql',
  null
),
(
  'new_moon_to_lions_gate_2026_evidence_contract_readback',
  'new_moon_to_lions_gate_2026_registration_queue',
  'db_query',
  'Three evidence-return contracts registered with exact attribution field requirements and no public claim allowance.',
  'select evidence_key, evidence_state, evidence_required, public_claim_allowed from public.c3_evidence_contract where evidence_key like ''%new_moon_to_lions_gate_2026''',
  '{"expected_evidence_contract_count":3,"public_claim_allowed":false}'::jsonb,
  'docs/oar/c3_field/register_new_moon_to_lions_gate_inanna_seat_initiative_v1.sql',
  null
),
(
  'new_moon_to_lions_gate_2026_baseline_artifact',
  'new_moon_to_lions_gate_2026_registration_queue',
  'file_check',
  'Baseline captured before mutation and saved as OAR evidence.',
  null,
  '{"baseline_path":"docs/oar/c3_field/baseline_new_moon_to_lions_gate_inanna_seat_initiative_v1.meta.md","captured_before_mutation":true}'::jsonb,
  'docs/oar/c3_field/baseline_new_moon_to_lions_gate_inanna_seat_initiative_v1.meta.md',
  null
),
(
  'new_moon_to_lions_gate_2026_oar1_closeout',
  'new_moon_to_lions_gate_2026_registration_queue',
  'file_check',
  'OAR1 closeout records exact registration scope, holds, readback, and next OAR2 recommendation.',
  null,
  '{"oar1_path":"docs/oar/c3_field/oar1_register_new_moon_to_lions_gate_inanna_seat_initiative_v1.meta.md"}'::jsonb,
  'docs/oar/c3_field/oar1_register_new_moon_to_lions_gate_inanna_seat_initiative_v1.meta.md',
  null
)
on conflict (evidence_key) do update set
  queue_key = excluded.queue_key,
  evidence_type = excluded.evidence_type,
  evidence_summary = excluded.evidence_summary,
  validation_query = excluded.validation_query,
  validation_result = excluded.validation_result,
  artifact_path = excluded.artifact_path,
  commit_hash = excluded.commit_hash;

commit;
