-- Seed Concordance Governance Expansion Seating v1
-- Source OAR2: docs/oar/c3_field/oar2_seed_concordance_governance_expansion_seating_v1.meta.md
-- Additive seating only. Do not alter schema.

insert into public.concordance_term (
  term_key,
  version_key,
  term_label,
  canonical_definition,
  axis,
  circuit,
  role,
  resolves_to,
  term_standing,
  visibility_standing,
  source_excerpt,
  metadata
) values
('seed_concordance_v1_constraints','seed_concordance_v1','Constraints','The observed invariants that govern behavior, recognition, and progression. Constraints are structural conditions, not imposed preferences.','governance',null,'invariant conditions','bounded valid operation','active','internal','Seed Concordance / Governance Layer / Constraints','{"expansion": "seed_concordance_governance_expansion_seating_v1"}'::jsonb),
('seed_concordance_v1_roles','seed_concordance_v1','Roles','The defined operational positions within the system. Roles remain distinct and may not collapse into one another.','governance',null,'operational position set','role integrity','active','internal','Seed Concordance / Governance Layer / Roles','{"expansion": "seed_concordance_governance_expansion_seating_v1"}'::jsonb),
('seed_concordance_v1_immutables','seed_concordance_v1','Immutables','The anchored conditions that may not be altered without breaking system coherence.','governance',null,'anchored non-alterable conditions','continuity across the circuit','active','internal','Seed Concordance / Governance Layer / Immutables','{"expansion": "seed_concordance_governance_expansion_seating_v1"}'::jsonb),
('seed_concordance_v1_verification','seed_concordance_v1','Verification','The process by which institutional alignment to Measures-defined order, progression, and conditions is confirmed prior to Recognition. Nothing is recognized as converted until verified.','governance',null,'alignment confirmation process','recognition eligibility','active','internal','System Concordance / Recognition / Verification and The 21 of Coherence / Verification Before Recognition','{"expansion": "seed_concordance_governance_expansion_seating_v1"}'::jsonb),
('seed_concordance_v1_recognition','seed_concordance_v1','Recognition','The external confirmation that full Measures Conversion has occurred. Recognition is not self-declared and is not inferred from activity, assets, or participation.','governance',null,'external confirmation surface','confirmed Measures Conversion','active','internal','System Concordance / Recognition and The 21 of Coherence / Verification Before Recognition','{"expansion": "seed_concordance_governance_expansion_seating_v1"}'::jsonb),
('seed_concordance_v1_dependency','seed_concordance_v1','Dependency','A relational condition that determines access or sequence. No unit exists in isolation.','governance',null,'access and sequence determinant','bounded access or sequence standing','active','internal','System Concordance / State Layer / Dependency','{"expansion": "seed_concordance_governance_expansion_seating_v1"}'::jsonb),
('seed_concordance_v1_state','seed_concordance_v1','State','The condition of a unit within the system. State is declared in Codex and rendered through Measures.','governance',null,'declared condition','rendered standing in Measures','active','internal','System Concordance / State Layer / State','{"expansion": "seed_concordance_governance_expansion_seating_v1"}'::jsonb)
on conflict (term_key) do nothing;

insert into public.concordance_relation (
  relation_key,
  version_key,
  source_ref,
  target_ref,
  relation_scope,
  relation_type,
  relation_label,
  relation_standing,
  visibility_standing,
  source_oar2_path,
  metadata
) values
('seed_concordance_v1_axis_constraints_governance','seed_concordance_v1','seed_concordance_v1_constraints','governance','term','axis','Constraints resolve to governance axis','active','internal','docs/oar/c3_field/oar2_seed_concordance_governance_expansion_seating_v1.meta.md','{"expansion": "seed_concordance_governance_expansion_seating_v1"}'::jsonb),
('seed_concordance_v1_role_constraints_invariants','seed_concordance_v1','seed_concordance_v1_constraints','invariant conditions','term','role','Constraints function as invariant conditions','active','internal','docs/oar/c3_field/oar2_seed_concordance_governance_expansion_seating_v1.meta.md','{"expansion": "seed_concordance_governance_expansion_seating_v1"}'::jsonb),
('seed_concordance_v1_resolves_constraints_bounded_operation','seed_concordance_v1','seed_concordance_v1_constraints','bounded valid operation','term','resolves_to','Constraints resolve to bounded valid operation','active','internal','docs/oar/c3_field/oar2_seed_concordance_governance_expansion_seating_v1.meta.md','{"expansion": "seed_concordance_governance_expansion_seating_v1"}'::jsonb),
('seed_concordance_v1_constraints_behavior','seed_concordance_v1','seed_concordance_v1_constraints','behavior','term','related_to','Constraints govern behavior','active','internal','docs/oar/c3_field/oar2_seed_concordance_governance_expansion_seating_v1.meta.md','{"expansion": "seed_concordance_governance_expansion_seating_v1", "relation_semantic": "governs"}'::jsonb),
('seed_concordance_v1_constraints_recognition','seed_concordance_v1','seed_concordance_v1_constraints','seed_concordance_v1_recognition','term','related_to','Constraints govern recognition','active','internal','docs/oar/c3_field/oar2_seed_concordance_governance_expansion_seating_v1.meta.md','{"expansion": "seed_concordance_governance_expansion_seating_v1", "relation_semantic": "governs"}'::jsonb),
('seed_concordance_v1_constraints_progression','seed_concordance_v1','seed_concordance_v1_constraints','progression','term','related_to','Constraints govern progression','active','internal','docs/oar/c3_field/oar2_seed_concordance_governance_expansion_seating_v1.meta.md','{"expansion": "seed_concordance_governance_expansion_seating_v1", "relation_semantic": "governs"}'::jsonb),
('seed_concordance_v1_axis_roles_governance','seed_concordance_v1','seed_concordance_v1_roles','governance','term','axis','Roles resolve to governance axis','active','internal','docs/oar/c3_field/oar2_seed_concordance_governance_expansion_seating_v1.meta.md','{"expansion": "seed_concordance_governance_expansion_seating_v1"}'::jsonb),
('seed_concordance_v1_role_roles_operational_positions','seed_concordance_v1','seed_concordance_v1_roles','operational position set','term','role','Roles function as operational position set','active','internal','docs/oar/c3_field/oar2_seed_concordance_governance_expansion_seating_v1.meta.md','{"expansion": "seed_concordance_governance_expansion_seating_v1"}'::jsonb),
('seed_concordance_v1_resolves_roles_integrity','seed_concordance_v1','seed_concordance_v1_roles','role integrity','term','resolves_to','Roles resolve to role integrity','active','internal','docs/oar/c3_field/oar2_seed_concordance_governance_expansion_seating_v1.meta.md','{"expansion": "seed_concordance_governance_expansion_seating_v1"}'::jsonb),
('seed_concordance_v1_roles_noncollapse','seed_concordance_v1','seed_concordance_v1_roles','role collapse prevention','term','related_to','Roles remain distinct and may not collapse into one another','active','internal','docs/oar/c3_field/oar2_seed_concordance_governance_expansion_seating_v1.meta.md','{"expansion": "seed_concordance_governance_expansion_seating_v1", "relation_semantic": "non_collapse"}'::jsonb),
('seed_concordance_v1_axis_immutables_governance','seed_concordance_v1','seed_concordance_v1_immutables','governance','term','axis','Immutables resolve to governance axis','active','internal','docs/oar/c3_field/oar2_seed_concordance_governance_expansion_seating_v1.meta.md','{"expansion": "seed_concordance_governance_expansion_seating_v1"}'::jsonb),
('seed_concordance_v1_role_immutables_anchored','seed_concordance_v1','seed_concordance_v1_immutables','anchored non-alterable conditions','term','role','Immutables function as anchored non-alterable conditions','active','internal','docs/oar/c3_field/oar2_seed_concordance_governance_expansion_seating_v1.meta.md','{"expansion": "seed_concordance_governance_expansion_seating_v1"}'::jsonb),
('seed_concordance_v1_resolves_immutables_continuity','seed_concordance_v1','seed_concordance_v1_immutables','continuity across the circuit','term','resolves_to','Immutables resolve to continuity across the circuit','active','internal','docs/oar/c3_field/oar2_seed_concordance_governance_expansion_seating_v1.meta.md','{"expansion": "seed_concordance_governance_expansion_seating_v1"}'::jsonb),
('seed_concordance_v1_immutables_coherence_boundary','seed_concordance_v1','seed_concordance_v1_immutables','seed_concordance_v1_coherence','term','related_to','Immutables may not be altered without breaking system coherence','active','internal','docs/oar/c3_field/oar2_seed_concordance_governance_expansion_seating_v1.meta.md','{"expansion": "seed_concordance_governance_expansion_seating_v1", "relation_semantic": "protects_continuity"}'::jsonb),
('seed_concordance_v1_axis_verification_governance','seed_concordance_v1','seed_concordance_v1_verification','governance','term','axis','Verification is seated in the governance layer','active','internal','docs/oar/c3_field/oar2_seed_concordance_governance_expansion_seating_v1.meta.md','{"expansion": "seed_concordance_governance_expansion_seating_v1"}'::jsonb),
('seed_concordance_v1_role_verification_alignment','seed_concordance_v1','seed_concordance_v1_verification','alignment confirmation process','term','role','Verification functions as alignment confirmation process','active','internal','docs/oar/c3_field/oar2_seed_concordance_governance_expansion_seating_v1.meta.md','{"expansion": "seed_concordance_governance_expansion_seating_v1"}'::jsonb),
('seed_concordance_v1_resolves_verification_eligibility','seed_concordance_v1','seed_concordance_v1_verification','recognition eligibility','term','resolves_to','Verification resolves to recognition eligibility','active','internal','docs/oar/c3_field/oar2_seed_concordance_governance_expansion_seating_v1.meta.md','{"expansion": "seed_concordance_governance_expansion_seating_v1"}'::jsonb),
('seed_concordance_v1_verification_before_recognition','seed_concordance_v1','seed_concordance_v1_verification','seed_concordance_v1_recognition','term','related_to','Recognition follows verification','active','internal','docs/oar/c3_field/oar2_seed_concordance_governance_expansion_seating_v1.meta.md','{"expansion": "seed_concordance_governance_expansion_seating_v1", "relation_semantic": "precedes"}'::jsonb),
('seed_concordance_v1_verification_measures_order','seed_concordance_v1','seed_concordance_v1_verification','seed_concordance_v1_measures','term','related_to','Verification confirms alignment to Measures-defined order, progression, and conditions','active','internal','docs/oar/c3_field/oar2_seed_concordance_governance_expansion_seating_v1.meta.md','{"expansion": "seed_concordance_governance_expansion_seating_v1", "relation_semantic": "measures_defined"}'::jsonb),
('seed_concordance_v1_axis_recognition_governance','seed_concordance_v1','seed_concordance_v1_recognition','governance','term','axis','Recognition is seated in the governance layer','active','internal','docs/oar/c3_field/oar2_seed_concordance_governance_expansion_seating_v1.meta.md','{"expansion": "seed_concordance_governance_expansion_seating_v1"}'::jsonb),
('seed_concordance_v1_role_recognition_confirmation','seed_concordance_v1','seed_concordance_v1_recognition','external confirmation surface','term','role','Recognition functions as external confirmation surface','active','internal','docs/oar/c3_field/oar2_seed_concordance_governance_expansion_seating_v1.meta.md','{"expansion": "seed_concordance_governance_expansion_seating_v1"}'::jsonb),
('seed_concordance_v1_resolves_recognition_conversion','seed_concordance_v1','seed_concordance_v1_recognition','confirmed Measures Conversion','term','resolves_to','Recognition resolves to confirmed Measures Conversion','active','internal','docs/oar/c3_field/oar2_seed_concordance_governance_expansion_seating_v1.meta.md','{"expansion": "seed_concordance_governance_expansion_seating_v1"}'::jsonb),
('seed_concordance_v1_recognition_measures_conversion','seed_concordance_v1','seed_concordance_v1_recognition','seed_concordance_v1_measures_conversion','term','related_to','Recognition occurs only upon full Measures Conversion','active','internal','docs/oar/c3_field/oar2_seed_concordance_governance_expansion_seating_v1.meta.md','{"expansion": "seed_concordance_governance_expansion_seating_v1", "relation_semantic": "requires"}'::jsonb),
('seed_concordance_v1_recognition_not_self_declared','seed_concordance_v1','seed_concordance_v1_recognition','self-declared status','term','related_to','Recognition is not self-declared','active','internal','docs/oar/c3_field/oar2_seed_concordance_governance_expansion_seating_v1.meta.md','{"expansion": "seed_concordance_governance_expansion_seating_v1", "relation_semantic": "excludes"}'::jsonb),
('seed_concordance_v1_axis_dependency_governance','seed_concordance_v1','seed_concordance_v1_dependency','governance','term','axis','Dependency is seated in the governance layer','active','internal','docs/oar/c3_field/oar2_seed_concordance_governance_expansion_seating_v1.meta.md','{"expansion": "seed_concordance_governance_expansion_seating_v1"}'::jsonb),
('seed_concordance_v1_role_dependency_access_sequence','seed_concordance_v1','seed_concordance_v1_dependency','access and sequence determinant','term','role','Dependency functions as access and sequence determinant','active','internal','docs/oar/c3_field/oar2_seed_concordance_governance_expansion_seating_v1.meta.md','{"expansion": "seed_concordance_governance_expansion_seating_v1"}'::jsonb),
('seed_concordance_v1_resolves_dependency_standing','seed_concordance_v1','seed_concordance_v1_dependency','bounded access or sequence standing','term','resolves_to','Dependency resolves to bounded access or sequence standing','active','internal','docs/oar/c3_field/oar2_seed_concordance_governance_expansion_seating_v1.meta.md','{"expansion": "seed_concordance_governance_expansion_seating_v1"}'::jsonb),
('seed_concordance_v1_dependency_access','seed_concordance_v1','seed_concordance_v1_dependency','access','term','related_to','Dependency determines access','active','internal','docs/oar/c3_field/oar2_seed_concordance_governance_expansion_seating_v1.meta.md','{"expansion": "seed_concordance_governance_expansion_seating_v1", "relation_semantic": "determines"}'::jsonb),
('seed_concordance_v1_dependency_sequence','seed_concordance_v1','seed_concordance_v1_dependency','sequence','term','related_to','Dependency determines sequence','active','internal','docs/oar/c3_field/oar2_seed_concordance_governance_expansion_seating_v1.meta.md','{"expansion": "seed_concordance_governance_expansion_seating_v1", "relation_semantic": "determines"}'::jsonb),
('seed_concordance_v1_dependency_non_isolation','seed_concordance_v1','seed_concordance_v1_dependency','seed_concordance_v1_quantum_entanglement','term','related_to','Dependency preserves that no unit exists in isolation','active','internal','docs/oar/c3_field/oar2_seed_concordance_governance_expansion_seating_v1.meta.md','{"expansion": "seed_concordance_governance_expansion_seating_v1", "relation_semantic": "non_isolation"}'::jsonb),
('seed_concordance_v1_axis_state_governance','seed_concordance_v1','seed_concordance_v1_state','governance','term','axis','State is seated in the governance layer','active','internal','docs/oar/c3_field/oar2_seed_concordance_governance_expansion_seating_v1.meta.md','{"expansion": "seed_concordance_governance_expansion_seating_v1"}'::jsonb),
('seed_concordance_v1_role_state_declared_condition','seed_concordance_v1','seed_concordance_v1_state','declared condition','term','role','State functions as declared condition','active','internal','docs/oar/c3_field/oar2_seed_concordance_governance_expansion_seating_v1.meta.md','{"expansion": "seed_concordance_governance_expansion_seating_v1"}'::jsonb),
('seed_concordance_v1_resolves_state_measures_standing','seed_concordance_v1','seed_concordance_v1_state','rendered standing in Measures','term','resolves_to','State resolves to rendered standing in Measures','active','internal','docs/oar/c3_field/oar2_seed_concordance_governance_expansion_seating_v1.meta.md','{"expansion": "seed_concordance_governance_expansion_seating_v1"}'::jsonb),
('seed_concordance_v1_state_declared_codex','seed_concordance_v1','seed_concordance_v1_state','seed_concordance_v1_codex','term','related_to','State is declared in Codex','active','internal','docs/oar/c3_field/oar2_seed_concordance_governance_expansion_seating_v1.meta.md','{"expansion": "seed_concordance_governance_expansion_seating_v1", "relation_semantic": "declared_in"}'::jsonb),
('seed_concordance_v1_state_rendered_measures','seed_concordance_v1','seed_concordance_v1_state','seed_concordance_v1_measures','term','related_to','State is rendered through Measures','active','internal','docs/oar/c3_field/oar2_seed_concordance_governance_expansion_seating_v1.meta.md','{"expansion": "seed_concordance_governance_expansion_seating_v1", "relation_semantic": "rendered_through"}'::jsonb)
on conflict (relation_key) do nothing;
