-- Seed Concordance Geometry Expansion Seating v1
-- Source OAR2: docs/oar/c3_field/oar2_seed_concordance_geometry_expansion_seating_v1.meta.md
-- Additive seating only. Do not alter schema.

insert into public.concordance_term (
  term_key,
  version_key,
  term_label,
  canonical_definition,
  axis,
  circuit,
  role,
  resolves_to,
  term_standing,
  visibility_standing,
  source_excerpt,
  metadata
) values
('seed_concordance_v1_orthogonal','seed_concordance_v1','Orthogonal','The condition of right-angle alignment across native layers. Orthogonal relation requires simultaneous validity across Codex, Field, Measures, and Chazz.','Coherence',null,'right-angle constraint','valid or rejected passage','active','internal','Seed Concordance / Geometry Layer / Orthogonal','{"expansion": "seed_concordance_geometry_expansion_seating_v1"}'::jsonb),
('seed_concordance_v1_orthocenter','seed_concordance_v1','Orthocenter','The point of convergence formed by valid orthogonal alignments. Orthocenter is resolved, not assigned.','Coherence','c3','converged formation point','Codex-ready state','active','internal','Seed Concordance / Geometry Layer / Orthocenter','{"expansion": "seed_concordance_geometry_expansion_seating_v1"}'::jsonb),
('seed_concordance_v1_relational_nodes','seed_concordance_v1','Relational Nodes','The positional points within Field where signal is located and related. Relational Nodes determine adjacency, dependency, sequence, and valid interaction pathways.','Field',null,'relational position points','correct placement in relation','active','internal','Seed Concordance / Geometry Layer / Relational Nodes','{"expansion": "seed_concordance_geometry_expansion_seating_v1"}'::jsonb),
('seed_concordance_v1_relational_vectors','seed_concordance_v1','Relational Vectors','The directional relations through which signal is positioned, linked, and moved within Field. Relational Vectors determine progression, return, dependency, correction, and direction of relation.','Field',null,'directional relation set','valid routing and placement','active','internal','Seed Concordance / Geometry Layer / Relational Vectors','{"expansion": "seed_concordance_geometry_expansion_seating_v1"}'::jsonb),
('seed_concordance_v1_isomorphism','seed_concordance_v1','Isomorphism','The condition in which a signal preserves identical structural relation across valid system layers. Isomorphism preserves exact relation and does not permit variation disguised as continuity.','Coherence','c1 c2 c3','structural continuity condition','single stable repeatable expression','active','internal','Seed Concordance / Geometry Layer / Isomorphism','{"expansion": "seed_concordance_geometry_expansion_seating_v1"}'::jsonb),
('seed_concordance_v1_isomorphic_appearance','seed_concordance_v1','Isomorphic Appearance','The relational rule that a coherent signal repeats its functional pattern orthogonally and without ambiguity. It is recurrence through preserved relation, not aesthetic duplication.','Coherence',null,'recurrence rule','stable placement through repeated structural truth','active','internal','Seed Concordance / Geometry Layer / Isomorphic Appearance','{"expansion": "seed_concordance_geometry_expansion_seating_v1"}'::jsonb)
on conflict (term_key) do nothing;

insert into public.concordance_relation (
  relation_key,
  version_key,
  source_ref,
  target_ref,
  relation_scope,
  relation_type,
  relation_label,
  relation_standing,
  visibility_standing,
  source_oar2_path,
  metadata
) values
('seed_concordance_v1_axis_orthogonal_coherence','seed_concordance_v1','seed_concordance_v1_orthogonal','seed_concordance_v1_coherence','term','axis','Orthogonal resolves to Coherence axis','active','internal','docs/oar/c3_field/oar2_seed_concordance_geometry_expansion_seating_v1.meta.md','{"expansion": "seed_concordance_geometry_expansion_seating_v1"}'::jsonb),
('seed_concordance_v1_role_orthogonal_right_angle','seed_concordance_v1','seed_concordance_v1_orthogonal','right-angle constraint','term','role','Orthogonal functions as right-angle constraint','active','internal','docs/oar/c3_field/oar2_seed_concordance_geometry_expansion_seating_v1.meta.md','{"expansion": "seed_concordance_geometry_expansion_seating_v1"}'::jsonb),
('seed_concordance_v1_resolves_orthogonal_passage','seed_concordance_v1','seed_concordance_v1_orthogonal','valid or rejected passage','term','resolves_to','Orthogonal resolves to valid or rejected passage','active','internal','docs/oar/c3_field/oar2_seed_concordance_geometry_expansion_seating_v1.meta.md','{"expansion": "seed_concordance_geometry_expansion_seating_v1"}'::jsonb),
('seed_concordance_v1_axis_orthocenter_coherence','seed_concordance_v1','seed_concordance_v1_orthocenter','seed_concordance_v1_coherence','term','axis','Orthocenter resolves to Coherence axis','active','internal','docs/oar/c3_field/oar2_seed_concordance_geometry_expansion_seating_v1.meta.md','{"expansion": "seed_concordance_geometry_expansion_seating_v1"}'::jsonb),
('seed_concordance_v1_circuit_orthocenter_c3','seed_concordance_v1','seed_concordance_v1_orthocenter','c3','term','circuit','Orthocenter resolves through c3 circuit','active','internal','docs/oar/c3_field/oar2_seed_concordance_geometry_expansion_seating_v1.meta.md','{"expansion": "seed_concordance_geometry_expansion_seating_v1"}'::jsonb),
('seed_concordance_v1_role_orthocenter_convergence','seed_concordance_v1','seed_concordance_v1_orthocenter','converged formation point','term','role','Orthocenter functions as converged formation point','active','internal','docs/oar/c3_field/oar2_seed_concordance_geometry_expansion_seating_v1.meta.md','{"expansion": "seed_concordance_geometry_expansion_seating_v1"}'::jsonb),
('seed_concordance_v1_resolves_orthocenter_codex_ready','seed_concordance_v1','seed_concordance_v1_orthocenter','Codex-ready state','term','resolves_to','Orthocenter resolves to Codex-ready state','active','internal','docs/oar/c3_field/oar2_seed_concordance_geometry_expansion_seating_v1.meta.md','{"expansion": "seed_concordance_geometry_expansion_seating_v1"}'::jsonb),
('seed_concordance_v1_axis_relational_nodes_field','seed_concordance_v1','seed_concordance_v1_relational_nodes','seed_concordance_v1_field','term','axis','Relational Nodes resolve to Field axis','active','internal','docs/oar/c3_field/oar2_seed_concordance_geometry_expansion_seating_v1.meta.md','{"expansion": "seed_concordance_geometry_expansion_seating_v1"}'::jsonb),
('seed_concordance_v1_role_relational_nodes_position','seed_concordance_v1','seed_concordance_v1_relational_nodes','relational position points','term','role','Relational Nodes function as relational position points','active','internal','docs/oar/c3_field/oar2_seed_concordance_geometry_expansion_seating_v1.meta.md','{"expansion": "seed_concordance_geometry_expansion_seating_v1"}'::jsonb),
('seed_concordance_v1_resolves_relational_nodes_placement','seed_concordance_v1','seed_concordance_v1_relational_nodes','correct placement in relation','term','resolves_to','Relational Nodes resolve to correct placement in relation','active','internal','docs/oar/c3_field/oar2_seed_concordance_geometry_expansion_seating_v1.meta.md','{"expansion": "seed_concordance_geometry_expansion_seating_v1"}'::jsonb),
('seed_concordance_v1_axis_relational_vectors_field','seed_concordance_v1','seed_concordance_v1_relational_vectors','seed_concordance_v1_field','term','axis','Relational Vectors resolve to Field axis','active','internal','docs/oar/c3_field/oar2_seed_concordance_geometry_expansion_seating_v1.meta.md','{"expansion": "seed_concordance_geometry_expansion_seating_v1"}'::jsonb),
('seed_concordance_v1_role_relational_vectors_direction','seed_concordance_v1','seed_concordance_v1_relational_vectors','directional relation set','term','role','Relational Vectors function as directional relation set','active','internal','docs/oar/c3_field/oar2_seed_concordance_geometry_expansion_seating_v1.meta.md','{"expansion": "seed_concordance_geometry_expansion_seating_v1"}'::jsonb),
('seed_concordance_v1_resolves_relational_vectors_routing','seed_concordance_v1','seed_concordance_v1_relational_vectors','valid routing and placement','term','resolves_to','Relational Vectors resolve to valid routing and placement','active','internal','docs/oar/c3_field/oar2_seed_concordance_geometry_expansion_seating_v1.meta.md','{"expansion": "seed_concordance_geometry_expansion_seating_v1"}'::jsonb),
('seed_concordance_v1_axis_isomorphism_coherence','seed_concordance_v1','seed_concordance_v1_isomorphism','seed_concordance_v1_coherence','term','axis','Isomorphism resolves to Coherence axis','active','internal','docs/oar/c3_field/oar2_seed_concordance_geometry_expansion_seating_v1.meta.md','{"expansion": "seed_concordance_geometry_expansion_seating_v1"}'::jsonb),
('seed_concordance_v1_circuit_isomorphism_c1_c2_c3','seed_concordance_v1','seed_concordance_v1_isomorphism','c1 c2 c3','term','circuit','Isomorphism operates through c1 c2 c3','active','internal','docs/oar/c3_field/oar2_seed_concordance_geometry_expansion_seating_v1.meta.md','{"expansion": "seed_concordance_geometry_expansion_seating_v1"}'::jsonb),
('seed_concordance_v1_role_isomorphism_continuity','seed_concordance_v1','seed_concordance_v1_isomorphism','structural continuity condition','term','role','Isomorphism functions as structural continuity condition','active','internal','docs/oar/c3_field/oar2_seed_concordance_geometry_expansion_seating_v1.meta.md','{"expansion": "seed_concordance_geometry_expansion_seating_v1"}'::jsonb),
('seed_concordance_v1_resolves_isomorphism_stable_expression','seed_concordance_v1','seed_concordance_v1_isomorphism','single stable repeatable expression','term','resolves_to','Isomorphism resolves to single stable repeatable expression','active','internal','docs/oar/c3_field/oar2_seed_concordance_geometry_expansion_seating_v1.meta.md','{"expansion": "seed_concordance_geometry_expansion_seating_v1"}'::jsonb),
('seed_concordance_v1_axis_isomorphic_appearance_coherence','seed_concordance_v1','seed_concordance_v1_isomorphic_appearance','seed_concordance_v1_coherence','term','axis','Isomorphic Appearance resolves to Coherence axis','active','internal','docs/oar/c3_field/oar2_seed_concordance_geometry_expansion_seating_v1.meta.md','{"expansion": "seed_concordance_geometry_expansion_seating_v1"}'::jsonb),
('seed_concordance_v1_role_isomorphic_appearance_recurrence','seed_concordance_v1','seed_concordance_v1_isomorphic_appearance','recurrence rule','term','role','Isomorphic Appearance functions as recurrence rule','active','internal','docs/oar/c3_field/oar2_seed_concordance_geometry_expansion_seating_v1.meta.md','{"expansion": "seed_concordance_geometry_expansion_seating_v1"}'::jsonb),
('seed_concordance_v1_resolves_isomorphic_appearance_stable_placement','seed_concordance_v1','seed_concordance_v1_isomorphic_appearance','stable placement through repeated structural truth','term','resolves_to','Isomorphic Appearance resolves to stable placement through repeated structural truth','active','internal','docs/oar/c3_field/oar2_seed_concordance_geometry_expansion_seating_v1.meta.md','{"expansion": "seed_concordance_geometry_expansion_seating_v1"}'::jsonb),
('seed_concordance_v1_geometry_orthogonal_codex_validity','seed_concordance_v1','seed_concordance_v1_orthogonal','seed_concordance_v1_codex','term','related_to','Orthogonal requires simultaneous validity across Codex','active','internal','docs/oar/c3_field/oar2_seed_concordance_geometry_expansion_seating_v1.meta.md','{"expansion": "seed_concordance_geometry_expansion_seating_v1", "relation_semantic": "depends_on"}'::jsonb),
('seed_concordance_v1_geometry_orthogonal_field_validity','seed_concordance_v1','seed_concordance_v1_orthogonal','seed_concordance_v1_field','term','related_to','Orthogonal requires simultaneous validity across Field','active','internal','docs/oar/c3_field/oar2_seed_concordance_geometry_expansion_seating_v1.meta.md','{"expansion": "seed_concordance_geometry_expansion_seating_v1", "relation_semantic": "depends_on"}'::jsonb),
('seed_concordance_v1_geometry_orthogonal_measures_validity','seed_concordance_v1','seed_concordance_v1_orthogonal','seed_concordance_v1_measures','term','related_to','Orthogonal requires simultaneous validity across Measures','active','internal','docs/oar/c3_field/oar2_seed_concordance_geometry_expansion_seating_v1.meta.md','{"expansion": "seed_concordance_geometry_expansion_seating_v1", "relation_semantic": "depends_on"}'::jsonb),
('seed_concordance_v1_geometry_orthogonal_chazz_validity','seed_concordance_v1','seed_concordance_v1_orthogonal','seed_concordance_v1_chazz','term','related_to','Orthogonal requires simultaneous validity across Chazz','active','internal','docs/oar/c3_field/oar2_seed_concordance_geometry_expansion_seating_v1.meta.md','{"expansion": "seed_concordance_geometry_expansion_seating_v1", "relation_semantic": "depends_on"}'::jsonb),
('seed_concordance_v1_geometry_orthocenter_orthogonal_convergence','seed_concordance_v1','seed_concordance_v1_orthocenter','seed_concordance_v1_orthogonal','term','related_to','Orthocenter is convergence formed by valid orthogonal alignments','active','internal','docs/oar/c3_field/oar2_seed_concordance_geometry_expansion_seating_v1.meta.md','{"expansion": "seed_concordance_geometry_expansion_seating_v1", "relation_semantic": "converges_with"}'::jsonb),
('seed_concordance_v1_geometry_nodes_adjacency','seed_concordance_v1','seed_concordance_v1_relational_nodes','adjacency','term','related_to','Relational Nodes determine adjacency','active','internal','docs/oar/c3_field/oar2_seed_concordance_geometry_expansion_seating_v1.meta.md','{"expansion": "seed_concordance_geometry_expansion_seating_v1", "relation_semantic": "positions"}'::jsonb),
('seed_concordance_v1_geometry_nodes_dependency','seed_concordance_v1','seed_concordance_v1_relational_nodes','dependency','term','related_to','Relational Nodes determine dependency','active','internal','docs/oar/c3_field/oar2_seed_concordance_geometry_expansion_seating_v1.meta.md','{"expansion": "seed_concordance_geometry_expansion_seating_v1", "relation_semantic": "depends_on"}'::jsonb),
('seed_concordance_v1_geometry_nodes_sequence','seed_concordance_v1','seed_concordance_v1_relational_nodes','sequence','term','related_to','Relational Nodes determine sequence','active','internal','docs/oar/c3_field/oar2_seed_concordance_geometry_expansion_seating_v1.meta.md','{"expansion": "seed_concordance_geometry_expansion_seating_v1", "relation_semantic": "positions"}'::jsonb),
('seed_concordance_v1_geometry_nodes_interaction_pathways','seed_concordance_v1','seed_concordance_v1_relational_nodes','valid interaction pathways','term','related_to','Relational Nodes determine valid interaction pathways','active','internal','docs/oar/c3_field/oar2_seed_concordance_geometry_expansion_seating_v1.meta.md','{"expansion": "seed_concordance_geometry_expansion_seating_v1", "relation_semantic": "routes"}'::jsonb),
('seed_concordance_v1_geometry_vectors_progression','seed_concordance_v1','seed_concordance_v1_relational_vectors','progression','term','related_to','Relational Vectors determine progression','active','internal','docs/oar/c3_field/oar2_seed_concordance_geometry_expansion_seating_v1.meta.md','{"expansion": "seed_concordance_geometry_expansion_seating_v1", "relation_semantic": "routes"}'::jsonb),
('seed_concordance_v1_geometry_vectors_return','seed_concordance_v1','seed_concordance_v1_relational_vectors','return','term','related_to','Relational Vectors determine return','active','internal','docs/oar/c3_field/oar2_seed_concordance_geometry_expansion_seating_v1.meta.md','{"expansion": "seed_concordance_geometry_expansion_seating_v1", "relation_semantic": "routes"}'::jsonb),
('seed_concordance_v1_geometry_vectors_dependency','seed_concordance_v1','seed_concordance_v1_relational_vectors','dependency','term','related_to','Relational Vectors determine dependency','active','internal','docs/oar/c3_field/oar2_seed_concordance_geometry_expansion_seating_v1.meta.md','{"expansion": "seed_concordance_geometry_expansion_seating_v1", "relation_semantic": "depends_on"}'::jsonb),
('seed_concordance_v1_geometry_vectors_correction','seed_concordance_v1','seed_concordance_v1_relational_vectors','correction','term','related_to','Relational Vectors determine correction','active','internal','docs/oar/c3_field/oar2_seed_concordance_geometry_expansion_seating_v1.meta.md','{"expansion": "seed_concordance_geometry_expansion_seating_v1", "relation_semantic": "routes"}'::jsonb),
('seed_concordance_v1_geometry_vectors_direction','seed_concordance_v1','seed_concordance_v1_relational_vectors','direction of relation','term','related_to','Relational Vectors determine direction of relation','active','internal','docs/oar/c3_field/oar2_seed_concordance_geometry_expansion_seating_v1.meta.md','{"expansion": "seed_concordance_geometry_expansion_seating_v1", "relation_semantic": "routes"}'::jsonb),
('seed_concordance_v1_geometry_isomorphic_appearance_orthogonal','seed_concordance_v1','seed_concordance_v1_isomorphic_appearance','seed_concordance_v1_orthogonal','term','related_to','Isomorphic Appearance repeats functional pattern orthogonally','active','internal','docs/oar/c3_field/oar2_seed_concordance_geometry_expansion_seating_v1.meta.md','{"expansion": "seed_concordance_geometry_expansion_seating_v1", "relation_semantic": "depends_on"}'::jsonb)
on conflict (relation_key) do nothing;
