import test from 'node:test';import assert from 'node:assert/strict';import {handleParagraph} from '../src/paragraph-adapter.js';import {preflightDev} from '../src/dev-preflight.js';
const identity={id:'leouxPnZrCGqMYqnboYx',slug:'undrifted'};const env={PARAGRAPH_PUBLISH_KEY:'test-only'};
const body={route_key:'route',publication_object_key:'publication',distribution_asset_id:'asset',authority_reference:'exact authority',idempotency_key:'occurrence',title:'Title',body_markdown:'Body',slug:'article',canonical_url:'https://measuresregistry.com/article',operator_confirmed:true,lapzuli_callable:true,channel_key:'paragraph_undrifted',channel_identifier:identity.id,dry_run:true,execute:false};
async function check(data,overrides={}){const original=globalThis.fetch;let writes=0;globalThis.fetch=async(url,options)=>{if(options.method==='POST')writes++;return Response.json(String(url).endsWith('/me')?identity:data)};try{const r=await handleParagraph(new Request('https://worker/paragraph/posts',{method:'POST',body:JSON.stringify({...body,...overrides})}),env);return {b:await r.json(),writes};}finally{globalThis.fetch=original}}
test('Paragraph duplicate on paginated inventory blocks write',async()=>{const r=await check({items:[{id:'prior',slug:'article'}],pagination:{hasMore:true,cursor:'next'}});assert.equal(r.b.standing,'HISTORICAL_OR_SUPERSEDED');assert.equal(r.writes,0)});
test('Paragraph incomplete duplicate inventory holds',async()=>{const r=await check({items:[],pagination:{hasMore:true,cursor:'repeat'}});assert.equal(r.b.standing,'held_paragraph_duplicate_coverage_incomplete');assert.equal(r.writes,0)});
test('Paragraph dry run validates complete inventory with zero effects',async()=>{const r=await check({items:[],pagination:{hasMore:false}});assert.equal(r.b.ok,true);assert.equal(r.b.external_publication_effects,0);assert.equal(r.writes,0)});
test('Paragraph live write requires atomic claim',async()=>{const r=await check({items:[],pagination:{hasMore:false}},{dry_run:false,execute:true});assert.equal(r.b.standing,'held_paragraph_atomic_claim_required');assert.equal(r.writes,0)});
test('DEV missing credential holds without network',async()=>{const r=await preflightDev({});assert.equal((await r.json()).standing,'held_dev_credential_missing')});
