export type WhitePaperDocument = {
  brand: string
  title: string
  subtitle: string
  abstract: string
  thesis: string
  publisher: string
  canonicalUrl: string
  relatedUrl: string
  relatedTitle: string
  paragraphs: string[]
}

export const communityPotential: WhitePaperDocument = {
  brand: "c3 Community Partners",
  title: "Community Potential",
  subtitle: "A Systems Model for Participation, Contribution, Creation, and Shared Value",
  abstract: "Large amounts of public funding, private capital, institutional capacity, labor, property, knowledge, and technology move through structures that do not consistently improve the lives of the people who rely on them. The problem is not only scarcity. It is also organization: resources may exist, yet remain disconnected from the people, places, and possibilities they are meant to support.",
  thesis: "Potential should not remain unrealized simply because the system around it cannot organize it.",
  publisher: "c3 Community Partners DAO, LLC",
  canonicalUrl: "https://c3field.online/community-potential",
  relatedUrl: "https://measuresregistry.com/governed-environments",
  relatedTitle: "Governed Environments",
  paragraphs: [
    "Abstract",
    "Large amounts of public funding, private capital, institutional capacity, labor, property, knowledge, and technology move through structures that do not consistently improve the lives of the people who rely on them. The problem is not only scarcity. It is also organization: resources may exist, yet remain disconnected from the people, places, and possibilities they are meant to support.",
    "c3 Community Partners begins from the premise that communities are not empty vessels waiting to be fixed. Communities already contain people with skills, ideas, relationships, tools, businesses, local knowledge, creative ability, and things they care about. Much of this potential remains unrealized because the surrounding structure does not make it visible, connectable, useful, or accountable to outcomes.",
    "This paper presents c3 Community Partners as a structured model for participation, connection, contribution, creation, recognition, shared value, and community return. c3 does not claim to have a universal answer. It proposes a repeatable way to organize community potential so that people and partners can see what exists, connect around shared purpose, contribute what they can, receive support where appropriate, and create outcomes that are transparent and verifiable.",
    "1. The Human Cost of Broken Systems",
    "Communities are surrounded by resources. Public funds, private capital, institutions, businesses, infrastructure, property, knowledge, labor, technology, creative talent, and social networks already exist in enormous quantities. Yet many people remain disconnected from the value those resources are meant to produce.",
    "Programs can be funded without building lasting local capacity. Institutions can measure activity without meaningfully improving outcomes. People can contribute time, labor, knowledge, care, and creativity while having little connection to the value that follows. The human cost is real: financial instability, isolation, burnout, loss of trust, limited opportunity, and a growing sense that the systems around us are difficult to influence and harder to understand.",
    "c3 Community Partners does not replace governments, institutions, businesses, nonprofits, or community organizations. It offers a structure that may help those existing capacities work together with greater clarity, participation, and accountability to outcomes.",
    "2. The c3 Premise",
    "The central premise is simple: potential already exists. The question is whether an environment can help make that potential visible, connected, useful, and shared. c3 treats unrealized community potential as an organizational problem before treating it as a technology problem.",
    "People are not reduced to users or profiles.",
    "Local resources are not treated as abstract inventory.",
    "Participation is not assumed to create responsibility.",
    "Contribution should be recognizable in what gets created.",
    "Outcomes should be transparent and verifiable.",
    "3. The c3 Model",
    "c3 identifies three minimal community functions. These are not branding stages. They are the basic movements through which community potential becomes actionable.",
    "Connect  ->  Contribute  ->  Create",
    "Connect",
    "Connect makes relevant people, resources, needs, places, and possibilities visible to one another. It creates the first structured encounter without assuming that every participant has already become a partner or project owner.",
    "Contribute",
    "Contribute allows people and partners to bring something meaningful into a shared effort: time, skill, place, tools, relationships, local knowledge, money, labor, creativity, or care. Contribution requires context; otherwise it becomes an unfocused request for help.",
    "Create",
    "Create turns connected contributions into something useful, measurable, and capable of producing an outcome. Creation may be economic, civic, artistic, educational, environmental, technological, or practical.",
    "4. Participation and Partnership",
    "Participation should be an open door, not a demand for immediate labor. A person may first participate by introducing themselves, sharing an interest, naming a need, offering a resource, or simply becoming visible within the environment.",
    "Partnership develops when participation becomes connected to shared purpose, responsibility, permission, and accountability. c3 Community Partners should therefore distinguish the person who is exploring from the partner who is helping carry an effort forward.",
    "5. How the Environment Works",
    "The environment establishes the conditions under which participation, contribution, and progression can occur. It should make the important things clear enough for people to understand and structured enough for records and outcomes to be reviewed.",
    "who is participating",
    "what people are responsible for",
    "what people have permission to do",
    "what was contributed",
    "what was created",
    "what outcome followed",
    "6. From Encounter to Recorded Outcome",
    "Relationships should move through clear steps rather than being assumed. A person may enter an encounter, choose whether to participate, provide consent where needed, complete relevant verification, and receive a recorded outcome. The purpose of the structure is not to make participation bureaucratic; it is to make important transitions understandable and reviewable.",
    "Encounter  ->  Participation  ->  Consent  ->  Verification  ->  Recorded Outcome",
    "A recorded outcome should reflect what actually occurred. A webpage, database entry, or automated system should not be able to manufacture participation, contribution, responsibility, or agreement simply because it is technically capable of writing a record.",
    "7. Contribution and Recognition",
    "The word attribution can carry too many meanings: credit, authorship, cause, blame, analytics, or source citation. c3 uses a narrower and more human concept: recognition of contribution.",
    "Recognition matters because contributions often disappear inside programs, institutions, or platforms. When people contribute to something meaningful, the resulting structure should be able to preserve what they brought and what it helped make possible.",
    "8. Shared Value and Community Return",
    "Ownership is a technical and legal term that should be used only where a true ownership interest is intended. In ordinary community language, c3 can often speak more clearly in terms of shared value, retained value, community return, benefit, stake, and continuity.",
    "More of the value created in a community should remain connected to the people and places that helped create it. That does not mean every contribution produces the same right or benefit. It means contribution, recognition, value, and return should be designed rather than left to disappear into outside structures.",
    "Contribution  ->  Recognition  ->  Shared Value  ->  Community Return",
    "9. Transparency and Verification",
    "Trust requires more than good intention. c3 should support records people can understand, review, and verify. Participation should not disappear behind institutional opacity, and outcomes should not depend on vague claims of impact.",
    "contributions can be reviewed",
    "decisions can be traced",
    "outcomes can be checked",
    "records remain understandable",
    "partners know what they are responsible for and what they have permission to decide",
    "10. The Million Dollar Mission",
    "The Million Dollar Mission is an applied test of the c3 model, not the definition of c3. The central question is whether significant capital placed into a community can be organized in a way that produces visible participation, meaningful contribution, local benefit, and retained value.",
    "The mission does not begin by claiming that money alone transforms a community. It asks whether capital can become more useful when it moves through a structured environment where people, resources, responsibilities, permissions, and outcomes are visible and connected.",
    "11. Replication Without Standardization",
    "A repeatable structure should not require communities to become identical. Different communities have different histories, industries, assets, needs, cultures, geography, and people. c3 should preserve those differences while making the organizing structure reusable.",
    "The pattern is simple: common environmental structure plus community-specific inputs produces a distinct community environment. This is not website cloning. It is a method for helping different communities organize their own potential through a common, understandable structure.",
    "12. What c3 Does Not Claim",
    "c3 Community Partners does not claim to replace government, institutions, businesses, nonprofits, or local leadership. It does not claim to solve poverty, know what every community needs, dictate outcomes, or guarantee success from participation alone.",
    "Its claim is more disciplined: c3 provides a structure for making community potential easier to see, connect, organize, recognize, and verify. That structure can support better participation and clearer community outcomes without pretending to own the answers.",
    "13. Conclusion",
    "People are carrying the consequences of systems that often fail to organize available resources around human outcomes. c3 Community Partners does not begin with the assumption that communities need to be fixed. It begins with the assumption that much of what they need may already be there: disconnected, unseen, underused, or unable to reach the people who could turn it into something meaningful.",
    "The work is to create conditions in which that potential can become visible, connected, contributive, useful, and shared. People participate. Partners connect around a purpose. Contributions are recognized. Outcomes are transparent and verifiable. Value has a better chance to remain connected to the people and places that helped create it.",
    "About c3 Community Partners",
    "c3 Community Partners DAO, LLC develops practical structures for helping people, local organizations, businesses, and resources connect around shared purpose, contribute with clear responsibility, and create value that can remain connected to the communities that helped produce it. The c3 model - Connect, Contribute, Create - is designed to support participation without treating people as platform inventory or assuming that participation transfers individual autonomy.",
    "Measures Registry is the first branch initiative of c3 Community Partners. It applies related systems principles to operational systems governance and the environments in which AI and other computational mechanisms are deployed.",
    "Publication note: Community Potential is White Paper 01 of c3 Community Partners. Public Release 1.0, September 2026. This paper describes a systems model and applied organizational direction; it does not constitute legal, investment, financial, or regulatory advice. Canonical public information: c3field.online."
  ]
}

export const governedEnvironments: WhitePaperDocument = {
  brand: "Measures Registry",
  title: "Governed Environments",
  subtitle: "Operational Systems Governance for AI and Computational Action",
  abstract: "Artificial intelligence governance increasingly addresses risk across organizations and across the AI lifecycle. Measures Registry addresses a narrower operational layer: the environment in which computational action is permitted, evidenced, executed, and allowed to persist.",
  thesis: "Reliable AI deployment depends on governing the environment in which computational action occurs, not merely the model, tool, or output.",
  publisher: "Measures Registry",
  canonicalUrl: "https://measuresregistry.com/governed-environments",
  relatedUrl: "https://c3field.online/community-potential",
  relatedTitle: "Community Potential",
  paragraphs: [
    "Abstract",
    "Artificial intelligence governance increasingly addresses risk across organizations and across the AI lifecycle. The NIST AI Risk Management Framework is intended for organizations designing, developing, deploying, or using AI systems, while ISO/IEC 42001 specifies an organizational management system for the responsible development and use of AI. Measures Registry addresses a narrower operational layer: the environment in which computational action is permitted, evidenced, executed, and allowed to persist.",
    "Measures Registry begins from the proposition that many apparent AI failures are environmental failures. It proposes an environmental approach to operational systems governance in which authority, execution, evidence, custody, passage, persistence, and computational capability are explicitly separated. This approach is intended to complement broader AI risk and management frameworks by making operational conditions inspectable at the point where action occurs.",
    "1. The Deployment Problem",
    "AI is increasingly introduced into systems that were not designed for autonomous or semi-autonomous computational actors. Organizations often begin with model choice, accuracy, prompting, and tool adoption. Those questions matter, but they are downstream of another:",
    "permissions and credentials",
    "APIs, databases, and tools",
    "workflows and human responsibilities",
    "infrastructure and undocumented dependencies",
    "operational drift and prior decisions",
    "2. Environmental Governance",
    "Measures Registry treats the environment as the principal operational governance surface. This does not replace lifecycle risk management, organizational policy, model evaluation, or regulatory compliance. It asks what must be true inside the operating environment before a computational action can be treated as permitted, attributable, and fit to persist.",
    "What exists?",
    "What may act, and under whose authority?",
    "Through which mechanism and against which state?",
    "Using what evidence and credentials?",
    "What may persist, and what must remain held?",
    "3. The Authority Wall",
    "A public or client renderer may initiate a request. It should not author authoritative state. Likewise, an agent, interface, integration, or automated tool should not be treated as an authority holder merely because it can reach an API, possess a credential, or execute a technically valid call.",
    "Request  →  Server Boundary  →  Environment  →  Authority  →  Prior State  →  Evidence  →  Permitted Transition  →  Persistence",
    "4. Environment-First Resolution",
    "Before asking what an actor may do, the system resolves the environment in which the action is being attempted. This reverses a common implementation tendency to treat identity or technical access as sufficient context and evaluate environmental conditions afterward.",
    "Environment  →  Environmental Conditions  →  Encounter Requirements  →  Standing  →  Permitted Action",
    "5. Evidence and State",
    "A database row may indicate that something happened. It does not necessarily establish that the action was permitted, that the evidence was sufficient, or that the resulting state should persist. Measures Registry therefore separates state, evidence, authority, passage, and persistence.",
    "6. Custody Boundaries",
    "Modern computational systems frequently collapse custody. A document is stored somewhere and therefore treated as authoritative; a secret exists somewhere and therefore its holder is treated as authorized. Measures Registry rejects these equivalences.",
    "source custody ≠ runtime delivery",
    "storage ≠ identity",
    "evidence custody ≠ participant authority",
    "credential custody ≠ computational authority",
    "7. Secrets and Computational Authority",
    "Credentials belong to execution environments. They should not belong to public renderers, participant records, documentation surfaces, or agents merely because those agents require access to perform a task. Technical possession of a secret is an execution fact, not a governance determination.",
    "8. Drift",
    "Operational systems change continuously. New tools are connected, permissions accumulate, processes are modified, employees create workarounds, integrations outlive their original purpose, and automated actions acquire new dependencies. AI systems then enter these environments and can expose, accelerate, or compound conditions that were already present.",
    "Measures Registry treats this as environmental drift: the environment no longer fully represents the system people believe they are operating.",
    "9. MAP the Environment",
    "MAP the Environment provides an applied institutional pathway for examining the operating environment before further deployment, optimization, or remediation. Its purpose is environmental visibility and operational mapping, not merely AI tool selection.",
    "operational map",
    "AI deployment inventory",
    "system relationships",
    "ownership and control",
    "drift and risk",
    "environmental constraints requiring alignment",
    "10. SEAT",
    "SEAT - System Environment Alignment Track - addresses the conditions that should be established before an environment is treated as aligned for its intended computational operations. Alignment is a demonstrated environmental condition, not a result conferred by assessment, payment, or technology adoption alone.",
    "11. The Registry Function",
    "Measures Registry preserves structured evidence concerning environments, measures, passage, authority, and standing. The public renderer manifests eligible state; it does not invent it. The registry function therefore separates what a user can see from what the governed system has actually determined.",
    "Source  →  Environmental Determination  →  Passage  →  Registry  →  Encounter  →  Renderer  →  Evidence",
    "12. Computational Agents",
    "Agentic AI makes environmental governance more urgent because agents increasingly determine intermediate steps, call tools, retrieve information, write records, invoke APIs, select actions, and persist results.",
    "13. Institutional Impact",
    "Environmental governance provides a practical way to address several operational risk classes simultaneously:",
    "authority confusion and frontend authority creep",
    "stale evidence and cross-environment state contamination",
    "uncontrolled agent actions and inappropriate persistence",
    "credential leakage and verification confusion",
    "undocumented AI deployment and operational drift",
    "14. Replicability",
    "Hospitals, manufacturers, governments, universities, financial institutions, small businesses, and technology companies do not have identical inputs. Environmental governance should therefore be replicable without pretending environments are identical.",
    "The structure may remain isomorphic. The inputs remain specific.",
    "15. Measures Registry Position",
    "Measures Registry is not principally an AI-policy system. It is an operational systems governance system concerned with the environment in which AI and other computational mechanisms act. Its focus is the point where organizational intent becomes executable action: authority, evidence, permitted transitions, custody, and persistence.",
    "Conclusion",
    "The next generation of AI governance cannot stop at models, policies, or outputs. It must reach the systems into which computational mechanisms act. Reliable computational action depends on an environment capable of distinguishing capability from authority, credentials from permission, records from evidence, storage from custody, passage from state, and execution from governance. Measures Registry proposes Governed System Integrity as the operational condition that makes optimized AI deployment possible without treating technical capability as permission.",
    "Relationship to c3 Community Partners",
    "c3 Community Partners applies governed-environment principles to community participation, contribution, creation, and locally retained value. Measures Registry, its first branch initiative, applies related principles to institutional systems and computational action. The domains differ; the shared structural premise is that the environment can be governed without absorbing the authority of every participant or actor within it.",
    "References and Publication Note",
    "National Institute of Standards and Technology (NIST). Artificial Intelligence Risk Management Framework (AI RMF 1.0). NIST AI 100-1, 2023. https://doi.org/10.6028/NIST.AI.100-1",
    "International Organization for Standardization / International Electrotechnical Commission. ISO/IEC 42001:2023, Information technology - Artificial intelligence - Management system, 2023.",
    "Autio, C., Schwartz, R., Dunietz, J., Jain, S., Stanley, M., Tabassi, E., Hall, P., & Roberts, K. Artificial Intelligence Risk Management Framework: Generative Artificial Intelligence Profile. NIST AI 600-1, 2024. https://doi.org/10.6028/NIST.AI.600-1",
    "Publication note: Governed Environments is a Measures Registry public white paper. Public Release 1.0, September 2026. Measures Registry is a registered branch initiative of c3 Community Partners DAO, LLC. Canonical public information: measuresregistry.com. This paper describes a systems-governance model and applied operational direction; it does not constitute legal, regulatory, cybersecurity, or compliance advice."
  ]
}
