insert into public.system_process_registry (
  process_key,
  process_title,
  process_family,
  process_scope,
  process_status,
  authority_level,
  source_reference_set,
  required_oar_type,
  requires_operator_confirm,
  requires_preflight,
  requires_oar1_closeout,
  title,
  status,
  source_path,
  authority_state,
  metadata
) values (
  'c3_field_chamber_directory_lapis_v1',
  'Lapis Chamber Directory',
  'chamber_directory',
  'docs/oar/c3_field/chamber_directories/lapis/lapis_chamber_directory_index_v1.meta.md',
  'active',
  'working',
  '[
    "docs/oar/c3_field/chamber_directories/oar2_register_lapis_chamber_directory_system_process_standing_v1.meta.md",
    "docs/oar/c3_field/chamber_directories/oar1_seat_chamber_directory_system_process_surface_and_run_db_schema_review_v1.meta.md",
    "docs/oar/c3_field/chamber_directories/lapis/lapis_chamber_directory_index_v1.meta.md"
  ]'::jsonb,
  'both',
  true,
  true,
  true,
  'Lapis Chamber Directory',
  'active',
  'docs/oar/c3_field/chamber_directories/lapis/lapis_chamber_directory_index_v1.meta.md',
  'working',
  '{
    "material_family": "lapis",
    "system_process_surface": "chamber_directory",
    "registration_state": "registered_after_readback",
    "public_facing": false,
    "authority": "system_process_surface",
    "working_directory_path": "docs/oar/c3_field/chamber_directories/lapis/",
    "index_path": "docs/oar/c3_field/chamber_directories/lapis/lapis_chamber_directory_index_v1.meta.md",
    "source_oar2": "docs/oar/c3_field/chamber_directories/oar2_register_lapis_chamber_directory_system_process_standing_v1.meta.md",
    "source_oar1": "docs/oar/c3_field/chamber_directories/oar1_seat_chamber_directory_system_process_surface_and_run_db_schema_review_v1.meta.md",
    "contract_families": [
      "public_encounter_contracts",
      "landing_page_design_contracts",
      "content_contracts",
      "media_contracts",
      "runtime_render_contracts",
      "cta_transition_contracts",
      "seo_contracts",
      "paragraph_contracts",
      "buffer_contracts",
      "social_distribution_contracts"
    ],
    "current_branch_use": [
      "measures_registry_public_landing",
      "undrifted_publication",
      "ai_operations_assessment",
      "structural_drift_legacy_trace"
    ],
    "disallowed_authority": [
      "public_brand",
      "public_route",
      "db_authority",
      "publication_authority",
      "landing_page_authority",
      "payment_surface",
      "c3_key_surface",
      "certification_surface",
      "conversion_surface",
      "dao_surface",
      "marble_readiness_surface"
    ]
  }'::jsonb
)
on conflict (process_key) do update
set process_title = excluded.process_title,
    process_family = excluded.process_family,
    process_scope = excluded.process_scope,
    process_status = excluded.process_status,
    authority_level = excluded.authority_level,
    source_reference_set = excluded.source_reference_set,
    required_oar_type = excluded.required_oar_type,
    requires_operator_confirm = excluded.requires_operator_confirm,
    requires_preflight = excluded.requires_preflight,
    requires_oar1_closeout = excluded.requires_oar1_closeout,
    title = excluded.title,
    status = excluded.status,
    source_path = excluded.source_path,
    authority_state = excluded.authority_state,
    metadata = coalesce(public.system_process_registry.metadata, '{}'::jsonb) || excluded.metadata,
    updated_at = now();
