insert into public.measures_persistence_state (
  persistence_key,
  process_key,
  oar2_key,
  environment_key,
  object_key,
  object_type,
  governed_state,
  source_sha256,
  evidence,
  custody,
  lineage,
  standing,
  next_permitted_transition,
  persisted_by,
  persisted_at,
  updated_at
) values (
  'c1me_canopy_reference_boundary_rule_v1:persistence',
  'governed_object_passage_process_v4',
  'capture_persist_c1me_canopy_reference_boundary_rule_chazz_001',
  'env_c3ops',
  'c1me_canopy_reference_boundary_rule_v1',
  'governance_clarification',
  jsonb_build_object(
    'environment_classification','c1ME.env',
    'canopy_reference_owner_controlled',true,
    'canopy_registry_standing_created',false,
    'canopy_is_c3_governed_relationship',false,
    'c3_external_account_access_created',false,
    'oauth_or_provider_token_authority_created',false,
    'external_read_authority_created',false,
    'external_write_authority_created',false,
    'external_scrape_or_sync_authority_created',false,
    'owner_directed_open_permitted',true,
    'open_action_scope','presentation_or_navigation_to_owner_supplied_external_url_only',
    'owner_operates_external_environment_directly',true,
    'owner_directed_share_preparation_permitted',true,
    'silent_promotion_to_registry_standing_prohibited',true,
    'c2_capability_created',false,
    'c3_capability_created',false,
    'runtime_effect_created',false,
    'implementation_authority_created',false
  ),
  null,
  jsonb_build_object(
    'operator','op044',
    'operator_instruction','capture>>persist',
    'execution_instance_id','capture_persist_c1me_canopy_reference_boundary_rule_chazz_001',
    'governance_artifact_commit','f966966a8fb7b85fcced8caf946afb13fe899bdf',
    'governance_artifact_blob_sha1','5b68b8b9eb123a190a1f2e283b2f64b99655d4cd',
    'source_concordance_control','current_source_concordance_v16',
    'source_impact','aligned_existing_semantics_no_source_supersession'
  ),
  jsonb_build_object(
    'physical_custody','github-private://c3codex/measures-of-inanna-governance/main/governance/c1me_canopy_reference_boundary_rule_v1.meta.md',
    'computational_custody','Measures Codex Registry',
    'custody_transfer',false,
    'ownership_transfer',false,
    'public_release',false
  ),
  jsonb_build_object(
    'append_preserving',true,
    'source_superseded',false,
    'primitive_grammar','my_environment_primitive_grammar_v0_1',
    'primitive_composition',jsonb_build_array('Subject','Environment','Selection','Boundary'),
    'environment_standing_rule','c1me_environment_current_standing_distinction_v1',
    'source_concordance_control','current_source_concordance_v16'
  ),
  'persisted_governance_clarification',
  'c1me_mgs_canopy_application',
  'op044_confirmed_computational_persistence',
  now(),
  now()
)
on conflict (persistence_key) do update set
  process_key = excluded.process_key,
  oar2_key = excluded.oar2_key,
  environment_key = excluded.environment_key,
  object_key = excluded.object_key,
  object_type = excluded.object_type,
  governed_state = excluded.governed_state,
  source_sha256 = excluded.source_sha256,
  evidence = excluded.evidence,
  custody = excluded.custody,
  lineage = excluded.lineage,
  standing = excluded.standing,
  next_permitted_transition = excluded.next_permitted_transition,
  persisted_by = excluded.persisted_by,
  updated_at = now();
