-- OAR2: oar2_finalize_undrifted_launch_projection_and_encounter_profile_v1
-- Projects the newly-canonical assessment_feature, section_labels, landing_design_contract
-- (now marked superseded), and encounter_profile from measures_publication_registry into
-- measures_encounter_def.metadata for encounter_key='undrifted'. Mirrors
-- scripts/regenerate-undrifted-encounter-projection.cjs's extended logic. Additive merge —
-- all other projected fields (issue_record, style_contract, featured_article_set, etc.,
-- already regenerated by the prior synchronization migration) are untouched.

update measures_encounter_def
set metadata = metadata || jsonb_build_object(
  'assessment_feature', (select metadata->'assessment_feature' from measures_publication_registry where publication_key = 'undrifted'),
  'section_labels', (select metadata->'section_labels' from measures_publication_registry where publication_key = 'undrifted'),
  'landing_design_contract', (select metadata->'landing_design_contract' from measures_publication_registry where publication_key = 'undrifted'),
  'encounter_profile', (select metadata->'encounter_profile' from measures_publication_registry where publication_key = 'undrifted'),
  'projection_meta', jsonb_build_object(
    'regenerated_at', now(),
    'regenerated_by_oar2', 'oar2_finalize_undrifted_launch_projection_and_encounter_profile_v1',
    'regeneration_script', 'scripts/regenerate-undrifted-encounter-projection.cjs',
    'canonical_sources', jsonb_build_array('measures_publication_registry','measures_publication_dispatch')
  )
)
where encounter_key = 'undrifted';
