insert into public.measures_publication_dispatch (
  publication_key,
  dispatch_key,
  title,
  dispatch_body,
  excerpt,
  seo_description,
  tags,
  primary_cta,
  secondary_cta,
  "references",
  media_manifest,
  internal_route,
  external_platform,
  external_slug,
  external_url,
  status,
  published_at,
  metadata,
  issue_number,
  article_url
) values
(
  'undrifted',
  'launch_cycle_001__paragraph__publication_001',
  'Field Findings 2026-W28',
  'Canonical article body remains in Assets/Articles/unDrifted/LaunchCycle001/registered/undrifted_field_findings_2026_w28_article_v1.md and the Measures Registry article projection.',
  'Weekly observations from the Field, July 4-10, 2026.',
  'Weekly observations from the Field, July 4-10, 2026.',
  jsonb_build_array('unDrifted','Field Findings','AI Governance','Structural Drift','Launch Cycle 001'),
  jsonb_build_object('label', 'Read on Measures Registry', 'url', 'https://measuresregistry.com/undrifted/field-findings-2026-w28'),
  jsonb_build_object('label', 'Read on Paragraph', 'url', 'https://paragraph.com/@undrifted/field-findings-2026-w28'),
  jsonb_build_array(
    jsonb_build_object('label', 'Measures Registry article route', 'url', 'https://measuresregistry.com/undrifted/field-findings-2026-w28'),
    jsonb_build_object('label', 'Paragraph publication', 'url', 'https://paragraph.com/@undrifted/field-findings-2026-w28')
  ),
  jsonb_build_object(
    'banner_image', 'measures-registry/field_findings_section_banner_2026_w28_v1.webp',
    'canonical_asset_path', 'Assets/Articles/unDrifted/LaunchCycle001/registered/undrifted_field_findings_2026_w28_article_v1.md'
  ),
  '/undrifted/field-findings-2026-w28',
  'paragraph',
  'field-findings-2026-w28',
  'https://paragraph.com/@undrifted/field-findings-2026-w28',
  'published',
  '2026-07-13T13:35:00Z',
  jsonb_build_object(
    'paragraph_post_id', '8UdwP2yt8pw9FacBWIbw',
    'paragraph_status', 'published',
    'paragraph_publication_slug', 'undrifted',
    'send_newsletter', false,
    'measures_registry_url', 'https://measuresregistry.com/undrifted/field-findings-2026-w28',
    'evidence_timestamp', '2026-07-13T13:35:00Z',
    'executor', 'Cody',
    'execution_mode', 'direct_paragraph_api_publish',
    'source_oar2', 'docs/oar/measures_registry/oar2_resume_launch_cycle_001_production_deployment_and_complete_publication_release_v1.meta.md'
  ),
  'Launch Cycle 001',
  'https://paragraph.com/@undrifted/field-findings-2026-w28'
),
(
  'undrifted',
  'launch_cycle_001__paragraph__publication_002',
  'AI Agents Are Not Entering Empty Systems',
  'Canonical article body remains in Assets/Articles/unDrifted/LaunchCycle001/registered/undrifted_response_001_ai_agents_are_not_entering_empty_systems_article_v1.md and the Measures Registry article projection.',
  'unDrifted Response 001.',
  'unDrifted Response 001.',
  jsonb_build_array('unDrifted','AI Agents','AI Governance','Structural Drift','Launch Cycle 001'),
  jsonb_build_object('label', 'Read on Measures Registry', 'url', 'https://measuresregistry.com/undrifted/ai-agents-are-not-entering-empty-systems'),
  jsonb_build_object('label', 'Read on Paragraph', 'url', 'https://paragraph.com/@undrifted/ai-agents-are-not-entering-empty-systems'),
  jsonb_build_array(
    jsonb_build_object('label', 'Measures Registry response route', 'url', 'https://measuresregistry.com/undrifted/ai-agents-are-not-entering-empty-systems'),
    jsonb_build_object('label', 'Paragraph publication', 'url', 'https://paragraph.com/@undrifted/ai-agents-are-not-entering-empty-systems'),
    jsonb_build_object('label', 'Related Field Findings', 'url', 'https://measuresregistry.com/undrifted/field-findings-2026-w28')
  ),
  jsonb_build_object(
    'banner_image', 'measures-registry/undrifted_response_section_banner_2026_w28_v1.webp',
    'canonical_asset_path', 'Assets/Articles/unDrifted/LaunchCycle001/registered/undrifted_response_001_ai_agents_are_not_entering_empty_systems_article_v1.md'
  ),
  '/undrifted/ai-agents-are-not-entering-empty-systems',
  'paragraph',
  'ai-agents-are-not-entering-empty-systems',
  'https://paragraph.com/@undrifted/ai-agents-are-not-entering-empty-systems',
  'published',
  '2026-07-13T13:40:00Z',
  jsonb_build_object(
    'paragraph_post_id', 'SRdBfqs0Xi4jr44T4r8o',
    'paragraph_status', 'published',
    'paragraph_publication_slug', 'undrifted',
    'send_newsletter', false,
    'measures_registry_url', 'https://measuresregistry.com/undrifted/ai-agents-are-not-entering-empty-systems',
    'related_field_findings_route', 'https://measuresregistry.com/undrifted/field-findings-2026-w28',
    'paragraph_related_link_status', 'not_present_in_live_paragraph_body',
    'measures_registry_related_link_status', 'present',
    'evidence_timestamp', '2026-07-13T13:40:00Z',
    'executor', 'Cody',
    'execution_mode', 'direct_paragraph_api_publish',
    'source_oar2', 'docs/oar/measures_registry/oar2_resume_launch_cycle_001_production_deployment_and_complete_publication_release_v1.meta.md'
  ),
  'Launch Cycle 001',
  'https://paragraph.com/@undrifted/ai-agents-are-not-entering-empty-systems'
)
on conflict (dispatch_key) do update set
  title = excluded.title,
  dispatch_body = excluded.dispatch_body,
  excerpt = excluded.excerpt,
  seo_description = excluded.seo_description,
  tags = excluded.tags,
  primary_cta = excluded.primary_cta,
  secondary_cta = excluded.secondary_cta,
  "references" = excluded."references",
  media_manifest = excluded.media_manifest,
  internal_route = excluded.internal_route,
  external_platform = excluded.external_platform,
  external_slug = excluded.external_slug,
  external_url = excluded.external_url,
  status = excluded.status,
  published_at = excluded.published_at,
  metadata = public.measures_publication_dispatch.metadata || excluded.metadata,
  issue_number = excluded.issue_number,
  article_url = excluded.article_url,
  updated_at = now();
