insert into public.measures_persistence_state (
  persistence_key,
  process_key,
  oar2_key,
  environment_key,
  object_key,
  object_type,
  governed_state,
  source_sha256,
  evidence,
  custody,
  lineage,
  standing,
  next_permitted_transition,
  persisted_by,
  persisted_at,
  updated_at
) values (
  'c1me_stephanie_target_binding_review_v0_1:persistence',
  'minimum_governed_standard_v1',
  'c1me_target_binding_review_chazz_001',
  'env_person_eea672f5a7676dad4316755b',
  'c1me_stephanie_target_binding_review_v0_1',
  'target_bound_mgs_binding_review',
  jsonb_build_object(
    'mgs_key','c1me_minimum_governed_standard_v0_1',
    'target_env_key','env_person_eea672f5a7676dad4316755b',
    'target_envpac_key','c3envpac_person_eea672f5a7676dad4316755b_v0_1',
    'subject_key','crs_93e901234ae044a396654ee80644b005',
    'circuit','c1',
    'current_result','C1',
    'relationship_standing','c1_C1_persisted',
    'c2_standing','not_created',
    'touchpoints',jsonb_build_object(
      'Identity','resolved',
      'Ownership','resolved',
      'Custody','resolved',
      'Verification','resolved',
      'Relationship','resolved',
      'Persistence','resolved'
    ),
    'dimension_results',jsonb_build_object(
      'Identity','pass',
      'Purpose','hold',
      'Authority','pass_with_boundary_note',
      'Boundary','hold',
      'Environment','pass',
      'Role','pass',
      'Relation','pass_with_nonoperative_package_note',
      'Passage','pass',
      'Standing','pass',
      'Evidence','pass',
      'Custody_and_lineage','pass',
      'Holds_and_failures','hold_recorded',
      'Return_and_review','pass',
      'Exit_condition','not_yet_satisfied'
    ),
    'hold_key','active_higher_order_capability_in_c1me',
    'conflicting_capability_key','sj_envpac_lapzuli_distribution',
    'conflicting_capability','lapzuli_distribution',
    'conflicting_action','prepare_distribution',
    'pubpac_reference_causes_hold',false,
    'pubpac_reference_rule','nonoperative_reference_only_no_c1_control_or_capability',
    'canopy_model_conflict',false,
    'runtime_effect_created',false,
    'capability_revoked',false,
    'package_deleted',false,
    'implementation_authority_created',false
  ),
  null,
  jsonb_build_object(
    'operator','op044',
    'operator_instruction','proceed',
    'execution_instance_id','c1me_target_binding_review_chazz_001',
    'governance_artifact_path','github-private://c3codex/measures-of-inanna-governance/main/governance/c1me_stephanie_target_binding_review_v0_1.meta.md',
    'governance_artifact_commit','5f1792d640ea70e5d984859d807859b492fa4d58',
    'mgs_profile','c1me_minimum_governed_standard_v0_1',
    'source_concordance_control','current_source_concordance_v16'
  ),
  jsonb_build_object(
    'physical_custody','github-private://c3codex/measures-of-inanna-governance/main/governance/c1me_stephanie_target_binding_review_v0_1.meta.md',
    'computational_custody','Measures Codex Registry',
    'custody_transfer',false,
    'ownership_transfer',false,
    'public_release',false
  ),
  jsonb_build_object(
    'append_preserving',true,
    'mgs_profile','c1me_minimum_governed_standard_v0_1',
    'canopy_boundary','c1me_canopy_reference_boundary_rule_v1',
    'standing_distinction','c1me_environment_current_standing_distinction_v1',
    'source_concordance_control','current_source_concordance_v16',
    'active_capability_observed','sj_envpac_lapzuli_distribution',
    'source_superseded',false
  ),
  'held_minimum_governed_standard_conflict',
  'separate_higher_order_capability_from_c1me_then_revalidate',
  'op044_confirmed_target_binding_review',
  now(),
  now()
)
on conflict (persistence_key) do update set
  process_key = excluded.process_key,
  oar2_key = excluded.oar2_key,
  environment_key = excluded.environment_key,
  object_key = excluded.object_key,
  object_type = excluded.object_type,
  governed_state = excluded.governed_state,
  source_sha256 = excluded.source_sha256,
  evidence = excluded.evidence,
  custody = excluded.custody,
  lineage = excluded.lineage,
  standing = excluded.standing,
  next_permitted_transition = excluded.next_permitted_transition,
  persisted_by = excluded.persisted_by,
  updated_at = now();
